# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-14 18:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hitter_Game_Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_date', models.DateField()),
                ('pa', models.IntegerField()),
                ('ab', models.IntegerField()),
                ('avg', models.FloatField()),
                ('h', models.IntegerField()),
                ('single', models.IntegerField()),
                ('double', models.IntegerField()),
                ('triple', models.IntegerField()),
                ('hr', models.IntegerField()),
                ('rbi', models.IntegerField()),
                ('bb', models.IntegerField()),
                ('k', models.IntegerField()),
                ('hbp', models.IntegerField()),
                ('sf', models.IntegerField()),
                ('slg', models.FloatField()),
                ('obp', models.FloatField()),
                ('war', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Hitter_Season_Stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g', models.IntegerField()),
                ('pa', models.IntegerField()),
                ('ab', models.IntegerField()),
                ('avg', models.FloatField()),
                ('h', models.IntegerField()),
                ('single', models.IntegerField()),
                ('double', models.IntegerField()),
                ('triple', models.IntegerField()),
                ('hr', models.IntegerField()),
                ('rbi', models.IntegerField()),
                ('bb', models.IntegerField()),
                ('k', models.IntegerField()),
                ('hbp', models.IntegerField()),
                ('sf', models.IntegerField()),
                ('slg', models.FloatField()),
                ('obp', models.FloatField()),
                ('ops', models.FloatField()),
                ('war', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Pitcher_Game_Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_date', models.DateField(default=datetime.date.today)),
                ('w', models.IntegerField()),
                ('l', models.IntegerField()),
                ('ip', models.FloatField()),
                ('bf', models.IntegerField()),
                ('er', models.IntegerField()),
                ('r', models.IntegerField()),
                ('h', models.IntegerField()),
                ('bb', models.IntegerField()),
                ('k', models.IntegerField()),
                ('hr', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pitcher_Season_Stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g', models.IntegerField()),
                ('w', models.IntegerField()),
                ('l', models.IntegerField()),
                ('sv', models.IntegerField()),
                ('ip', models.FloatField()),
                ('whip', models.FloatField()),
                ('k_per_nine', models.FloatField()),
                ('k', models.IntegerField()),
                ('bb_per_nine', models.FloatField()),
                ('hr_per_nine', models.FloatField()),
                ('babip', models.FloatField()),
                ('era', models.FloatField()),
                ('fip', models.FloatField()),
                ('x_fip', models.FloatField()),
                ('war', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('position', models.CharField(max_length=15)),
                ('team', models.CharField(max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='pitcher_season_stats',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rangerstats.Player'),
        ),
        migrations.AddField(
            model_name='pitcher_game_record',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rangerstats.Player'),
        ),
        migrations.AddField(
            model_name='hitter_season_stats',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rangerstats.Player'),
        ),
        migrations.AddField(
            model_name='hitter_game_record',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rangerstats.Player'),
        ),
    ]
