# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-30 20:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rangerstats', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hitter_game_record',
            name='war',
        ),
        migrations.AddField(
            model_name='hitter_game_record',
            name='wrc_plus',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
